# These are supported funding model platforms

github: eltman93 - https://eltman93.github.com
ko_fi: eltman93 - https://ko-fi.com/eltman93
As a patron: Pitt Theatre - https://pitttheater.com/index.html
Directly on PayPal: https://www.paypal.me/eltman93?locale.x=en_US
